# Generated by Django 2.2.9 on 2020-02-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0003_reading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
