# Generated by Django 2.2.9 on 2020-02-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0005_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='measurement_type',
            field=models.CharField(default='count', max_length=200),
            preserve_default=False,
        ),
    ]
