# Generated by Django 2.2.9 on 2020-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0007_remove_reading_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
