# Generated by Django 2.2.9 on 2020-02-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0008_auto_20200203_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='Change me', max_length=15),
        ),
        migrations.AddField(
            model_name='school',
            name='color',
            field=models.CharField(default='bg-primary', max_length=25),
        ),
    ]
