# Generated by Django 2.2.9 on 2020-02-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0009_auto_20200213_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='color',
            new_name='colour',
        ),
    ]
