# Generated by Django 2.2.9 on 2020-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susschool', '0011_auto_20200305_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
